_target_: src.models.lrw_module.LRWLitModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.components.simple_video_net.VideoConv
  in_channels: 1 
  kernel_size: 3
  stride: 1
  padding: 1 
  dilation: 0
